<?php

namespace AppBundle\Repository;

/**
 * AudioSheetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AudioSheetRepository extends SheetRepository
{
}
