<?php

namespace AppBundle\Repository;

/**
 * SheetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SheetRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAll(){
        $qb = $this->createQueryBuilder('s');

        $result = $qb->getQuery()->execute();

        return $result;
    }

    public function getVinyl(){
        $qb = $this->createQueryBuilder('s');

        $query = $qb->where('s.type = :type')
            ->setParameter('type', 'Vinyl');

        $result = $query->getQuery()->execute();

        return $result;
    }
}
